get-appxpackage *messaging* -allusers | remove-appxpackage
get-appxpackage *sway* -allusers | remove-appxpackage
get-appxpackage *commsphone* -allusers | remove-appxpackage
get-appxpackage *windowsphone* -allusers | remove-appxpackage
get-appxpackage *phone* -allusers | remove-appxpackage
get-appxpackage *communicationsapps* -allusers | remove-appxpackage
get-appxpackage *people* -allusers | remove-appxpackage
get-appxpackage *zunemusic* -allusers | remove-appxpackage
get-appxpackage *zunevideo* -allusers | remove-appxpackage
get-appxpackage *zune* -allusers | remove-appxpackage
get-appxpackage *bingfinance* -allusers | remove-appxpackage
get-appxpackage *bingnews* -allusers | remove-appxpackage
get-appxpackage *bingsports* -allusers | remove-appxpackage
get-appxpackage *bingweather* -allusers | remove-appxpackage
get-appxpackage *bing* -allusers | remove-appxpackage
get-appxpackage *onenote* -allusers | remove-appxpackage
get-appxpackage *alarms* -allusers | remove-appxpackage
get-appxpackage *camera* -allusers | remove-appxpackage
get-appxpackage *photos* -allusers | remove-appxpackage
get-appxpackage *maps* -allusers | remove-appxpackage
get-appxpackage *soundrecorder* -allusers | remove-appxpackage
get-appxpackage *xbox* -allusers | remove-appxpackage
get-appxpackage *solitaire* -allusers | remove-appxpackage
get-appxpackage *officehub* -allusers | remove-appxpackage
get-appxpackage *skypeapp* -allusers | remove-appxpackage
get-appxpackage *getstarted* -allusers | remove-appxpackage
get-appxpackage *3dbuilder* -allusers | remove-appxpackage
 